// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using f4872.Data;

#nullable disable

namespace f4872.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260903213412_GuardarLosIngredientesQueSeSacan")]
    partial class GuardarLosIngredientesQueSeSacan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("f4872.Models.Base", b =>
                {
                    b.Property<int>("IdBase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBase"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("Rinde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("IdBase");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Bases", t =>
                        {
                            t.HasCheckConstraint("CK_Bases_Rinde", "\"Rinde\" > 0");
                        });
                });

            modelBuilder.Entity("f4872.Models.BaseIngrediente", b =>
                {
                    b.Property<int>("IdBase")
                        .HasColumnType("integer");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("IdBase", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("BaseIngredientes", t =>
                        {
                            t.HasCheckConstraint("CK_BaseIngredientes_Cantidad", "\"Cantidad\" > 0");
                        });
                });

            modelBuilder.Entity("f4872.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdIngrediente"));

                    b.Property<decimal?>("CantidadDeCompra")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<bool>("Libre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal?>("PrecioDeCompra")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdIngrediente");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("f4872.Models.ItemPedido", b =>
                {
                    b.Property<int>("IdItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItemPedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("UnidadesPorPack")
                        .HasColumnType("integer");

                    b.HasKey("IdItemPedido");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProducto");

                    b.ToTable("ItemPedidos", t =>
                        {
                            t.HasCheckConstraint("CK_ItemPedidos_Cantidad", "\"Cantidad\" > 0");

                            t.HasCheckConstraint("CK_ItemPedidos_Pack", "\"UnidadesPorPack\" IS NULL OR \"UnidadesPorPack\" > 0");

                            t.HasCheckConstraint("CK_ItemPedidos_Precio", "\"PrecioUnitario\" >= 0");
                        });
                });

            modelBuilder.Entity("f4872.Models.ItemQuitado", b =>
                {
                    b.Property<int>("IdItemPedido")
                        .HasColumnType("integer");

                    b.Property<string>("Ingrediente")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("IdItemPedido", "Ingrediente");

                    b.ToTable("ItemQuitados");
                });

            modelBuilder.Entity("f4872.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("IdPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("f4872.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("IdBase")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdBase");

                    b.HasIndex("Familia", "Nombre")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("f4872.Models.ProductoIngrediente", b =>
                {
                    b.Property<int>("IdProducto")
                        .HasColumnType("integer");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<bool>("Quitable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("IdProducto", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("ProductoIngredientes", t =>
                        {
                            t.HasCheckConstraint("CK_ProductoIngredientes_Cantidad", "\"Cantidad\" > 0");
                        });
                });

            modelBuilder.Entity("f4872.Models.BaseIngrediente", b =>
                {
                    b.HasOne("f4872.Models.Base", "Base")
                        .WithMany("Receta")
                        .HasForeignKey("IdBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("f4872.Models.Ingrediente", "Ingrediente")
                        .WithMany("UsosEnBases")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Base");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("f4872.Models.ItemPedido", b =>
                {
                    b.HasOne("f4872.Models.Pedido", "Pedido")
                        .WithMany("Items")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("f4872.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("f4872.Models.ItemQuitado", b =>
                {
                    b.HasOne("f4872.Models.ItemPedido", "Item")
                        .WithMany("Quitados")
                        .HasForeignKey("IdItemPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("f4872.Models.Producto", b =>
                {
                    b.HasOne("f4872.Models.Base", "Base")
                        .WithMany("Productos")
                        .HasForeignKey("IdBase")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Base");
                });

            modelBuilder.Entity("f4872.Models.ProductoIngrediente", b =>
                {
                    b.HasOne("f4872.Models.Ingrediente", "Ingrediente")
                        .WithMany("UsosEnProductos")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("f4872.Models.Producto", "Producto")
                        .WithMany("Receta")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("f4872.Models.Base", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("f4872.Models.Ingrediente", b =>
                {
                    b.Navigation("UsosEnBases");

                    b.Navigation("UsosEnProductos");
                });

            modelBuilder.Entity("f4872.Models.ItemPedido", b =>
                {
                    b.Navigation("Quitados");
                });

            modelBuilder.Entity("f4872.Models.Pedido", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("f4872.Models.Producto", b =>
                {
                    b.Navigation("Receta");
                });
#pragma warning restore 612, 618
        }
    }
}
